name : Github Actions - Push - Path Template
run-name : Running - ${{ github.event_name }}
on: 
  push:
     paths:
      -'**.txt'

jobs: 
   on-push:
    runs-on: ubuntu-latest
    steps :
     - name: Comentario
       run: | 
        echo "Coment√°rio push workflow - path"
        echo "Executando"
